/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cane(props) {
  const { nodes, materials } = useGLTF('models/cane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.IvoryPalmTree_mesh.geometry} material={materials.IvoryCanePalmTree_mat} />
    </group>
  )
}

useGLTF.preload('models/cane.glb')
