/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/palm.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Palm(props) {
  const { nodes, materials } = useGLTF('models/palm.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.QueenPalmTree_Mesh.geometry} material={materials['QueenPalmTree:QueenPalmTree_mat']} />
    </group>
  )
}

useGLTF.preload('models/palm.glb')
