/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/tree.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('models/tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh1406566609.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1406566609_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1406566609_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1406566609_3.geometry} material={materials.mat9} />
    </group>
  )
}

useGLTF.preload('models/tree.glb')
